### ISSUE TITLE
abbreviated output for data.frame is wrong

### ISSUE THREAD

**Issue by janschulz** [IRkernel/repr#28]
I've a data frame (> 100 rows) which is abbreviated when I print it with `full_df %>% select(raw_lname, raw_fname)`. But the index is not showing the right numbers but the numbers in the current data frame:

```
1
2
[...]
29
30
...
32
33
[...]
60
61
```

-> It doesn't show the real row number but the one from the printed frame :-(

**Comment by karldw** [comment]
It's possible I broke this when I was fixing things in [the array abbreviating function](https://github.com/IRkernel/repr/blob/master/R/repr_matrix_df.r#L36).  Can you tell me more about how this output is wrong?  In particular, I'm not sure I understand the phrase "the index is not showing the right numbers but the numbers in the current data frame".

**Comment by JanSchulz** [comment]
I would expect that the index shows the row number in the old dataframe or none. So

1
2
[...]
29
30
...
150
151
[...]
180
181

**Comment by karldw** [comment]
I think this was fixed along with #31.  @JanSchulz, can you confirm?

**Comment by JanSchulz** [comment]
Nope, still the same behavior, I think I tracked it down to the use of the readr package:

```
ensure.package("dplyr")
ensure.package("readr")
df = data.frame(a=c(1:1000, 1111111111111), b=1:1001)
write_csv(df, "test_delete.csv")
df2 = read_csv("test_delete.csv")
#df2 %>% select(a) %>% glimpse()
df %>% select(a) # ok
df2 %>% select(a) # no ok...
```

**Comment by karldw** [comment]
Interesting, thanks.  I think it's something with the way repr shortens dplyr's `tbl_df`s.  For instance, this code has the same problem:
```R
library(dplyr)
df <- data.frame(a=c(1:1000, 111111), b=1:1001)
df2 <- tbl_df(df)
df  # ok
df2  # not ok
```

**Comment by karldw** [comment]
The problem is that dplyr automatically reassigns row names, which makes a ton of sense, but causes a bit of hassle here.  The problem should be fixed whenever my current set of commits is merged in.

**Comment by janschulz** [comment]
Confirmed as fixed in a dataframe and with dplyr. Closing. 

@karldw Thanks!

**Comment by janschulz** [comment]
Ok, I take that back:

```R
library("dplyr")
data.frame(a=1:200, b=201:400) %>% select(a)
[... shortend...]
27        27
28        28
29        29
30        30
<U+22EE>   <U+22EE>
171      171
172      172
173      173
174      174
[...shortend...]
```

In the html output it's fine...

**Comment by janschulz** [comment]
Is this https://github.com/IRkernel/repr/issues/21?

**Comment by karldw** [comment]
Maybe?  I don't run into your issue with Firefox or Chromium on Ubuntu.

![screenshot from 2016-04-11 08-29-28](https://cloud.githubusercontent.com/assets/12504708/14432696/204a29ba-ffc0-11e5-90c8-15871f820725.png)

**Comment by flying-sheep** [comment]
OK, looks like it. thanks!

**Comment by janschulz** [comment]
With me, it's still broken!

@karldw are you on linux? IF yes, this is "just" #21 again... If so we should replace the char with somethign which works on windows as well...

**Comment by flying-sheep** [comment]
> @karldw are you on linux? If yes, this is "just" #21 again...

this is why i closed it:

> I don't run into your issue with Firefox or Chromium on **Ubuntu**

you have missed that part :grin:

**Comment by janschulz** [comment]
Oups, yes... should go home...

**Comment by janschulz** [comment]
Ok, it doesn't look like #21 will be fixed soon, so we should change the char: https://github.com/hadley/evaluate/issues/66#issuecomment-208571265

**Comment by flying-sheep** [comment]
nooooooooooooooooooooooooooooooooooooooooooooooooooo

**Comment by flying-sheep** [comment]
no

**Comment by flying-sheep** [comment]
no fucking windows preventing us from having pretty things.

if you want you can create code that detects if the character is supported and replaces it if it isn’t. with your strlen checking, there’s a good avenue for this.

**Comment by janschulz** [comment]
This check doesn't work, you would have to print it in a captur.output... Is it such a problem to just use three dots?

**Comment by flying-sheep** [comment]
yes!

**Comment by janschulz** [comment]
This works on my windows box:

```R
char_fallback <- function(char, default) {
  real_len <- nchar(char)
  r_len <- nchar(capture.output(cat(char)))
  if (real_len == r_len) char else default
}
ellip.h <- char_fallback('\u22EF', '...')
ellip.v <- char_fallback('\u22EE', ellip.h)
ellip.d <- char_fallback('\u22F1', '')
```

If you go that way, you could also do something like this in the executer:

```
if(.Platform$OS.type == "windows") {
  issue_warning_if_bad_unicode <- function(code){
    real_len <- nchar(code)
    r_len <- nchar(capture.output(cat(code)))
    if (real_len != r_len){
      display_error("Your code contains a unicode char which is not displayable in your current locale. This can lead to subtile errors if you use such chars to do comparisons. Please see ...")
    }
  }
} else {
   # Nothing on other systems
  issue_warning_if_bad_unicode <- function(code) NULL
}
issue_warning_if_bad_unicode(code)
```

**Comment by flying-sheep** [comment]
`display_error()` would be `warning()` :wink:

**Comment by janschulz** [comment]
I'm not sure if the warning would end up in the right place in the frontend...

> and your idea is to call that function every time something is executed?

Yes, only on windows and maybe configurable.

I'm a big fan of "explicit error messages": better do a check too many (or a fallback) than getting obscure error messages or errors in places where it's not obvious what went wrong...

**Comment by flying-sheep** [comment]
ah, good. we should create a `display_error` method for the Executor then and call it from `handle_display_error` and when the code has unicode and people are on shitty OSs :stuck_out_tongue_winking_eye:

**Comment by janschulz** [comment]
more `display_stream(..., stream=c('stdout', 'stderr'))`, but this could also simple be a private helper in the irkernel package.

**Comment by janschulz** [comment]
If you want, just go ahead, I won't work on this until wednesday evening...

**Comment by janschulz** [comment]
Ok, on it...

**Comment by flying-sheep** [comment]
:+1: sorry, wasn’t in the mood
